"""Loading Subject model test

Revision ID: b6b156bdac33
Revises: d79b31a0dcdb
Create Date: 2023-02-28 12:24:55.176697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b6b156bdac33"
down_revision = "d79b31a0dcdb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
