"""Add project-subject relationship

Revision ID: de5502fb44fb
Revises: 93df265c1c6c
Create Date: 2023-03-03 12:39:35.292411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5502fb44fb'
down_revision = '93df265c1c6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
